
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />
<m:item name='SiteMap地图' link='map.php' rank='plus_Sitemap' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />

