<?php
$z[0]=Array("litpic","",89,104);
$z[1]=Array("fulltitle","",111,129);
$z[2]=Array("typename","",185,202);
$z[3]=Array("arcurl","",234,249);
$z[4]=Array("fulltitle","",275,293);
$z[5]=Array("arcurl","",324,339);
$z[6]=Array("title","",341,355);
$z[7]=Array("info","",370,383);
$z[8]=Array("click","",405,419);
$z[9]=Array("pubdate","",432,483);
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";

?>