<div class="hotbox">
	<div class="hotimg">
		<div class="hotimgzz"></div>
		<img src="[field:litpic/]" alt="[field:fulltitle/]" width="250" height="165"/>
		<div class="standpoint">[field:typename/]</div>
		<a class="zzsz" href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]"></a>
	</div>
	<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
	<p>[field:info/]...</p>
	<span>ÔÄ¶Á£º[field:click/]</span><span>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</span> 
  </div>