<li><strong><a href="{dede:field name='typeurl'/}" title="" target="_self"><span class="glyphicon 
glyphicon-book"></span>&nbsp;&nbsp;{dede:field name='typename'/}</a></strong>
                        <dl>
					<em></em>
                    {dede:channel type='son' noself='yes'}
					<dd><a href="[field:typelink/]" title="" target="_self">[field:typename/]</a></dd>
                    {/dede:channel}
				</dl></li>