<?php
$z[0]=Array("global","@me=(@me+1)%2==0?'':'chosenbox-ml';",22,114);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",154,169);
$z[2]=Array("fulltitle","",178,196);
$z[3]=Array("litpic","",224,239);
$z[4]=Array("fulltitle","",246,264);
$z[5]=Array("arcurl","",320,335);
$z[6]=Array("fulltitle","",344,362);
$z[7]=Array("fulltitle","",380,398);
$z[8]=Array("info","",415,428);

?>