<div class="chosenbox [field:global name=autoindex runphp='yes']@me=(@me+1)%2==0?'':'chosenbox-ml';[/field:global]">
			<div class="chosenimg"><a href="/[field:arcurl/]" title="[field:fulltitle/]" target="_blank"><img src="[field:litpic/]" alt="[field:fulltitle/]" width="130" height="85" /></a></div>
			<h3><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:fulltitle/]</a></h3>
			<p>[field:info/]...</p>
			<p><span></span></p>
		</div>