<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",116,142);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n			<li><strong><a href=\"{dede:field name='typeurl'/}\" title=\"\" target=\"_self\"><span class=\"glyphicon \r\nglyphicon-book\"></span>&nbsp;&nbsp;{dede:field name='typename'/}</a></strong>\r\n                        <dl>\r\n					<em></em>\r\n                    {dede:channel type='son' noself='yes'}\r\n					<dd><a href=\"[field:typelink/]\" title=\"\" target=\"_self\">[field:typename/]</a></dd>\r\n                    {/dede:channel}\r\n				</dl></li>\r\n      ",322,816);
$z[2][4]['typeid']="top";
$z[3]=Array("type","[field:typeurl /]",881,933);
$z[3][4]['typeid']="16";

?>